# -*- coding: utf-8 -*-
"""cv_lab4_q1._keypoint_matches_return.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1u31kFz24AGtKon_fKTRe_-zQ13Y1OmNz
"""

# Commented out IPython magic to ensure Python compatibility.
import cv2 
import matplotlib.pyplot as plt
# %matplotlib inline

img1 = cv2.imread('./boat1.pgm',-1) 

img2 = cv2.imread('./boat2.pgm',-1)

#define a function that returns the keypoint descriptors
'''1. Create a function that takes image pairs boat1.pgm and boat2.pgm as input,
and return the keypoint matchings between the two images. Name your script
as keypoint matching.py.'''


def keypoint_matchings(img1, img2):

  #sift
  sift = cv2.xfeatures2d.SIFT_create()

  k1, d1 = sift.detectAndCompute(img1,None)
  k2, d2 = sift.detectAndCompute(img2,None)

  bf = cv2.BFMatcher()
  matches = bf.knnMatch(d1,d2, k=2)



  good_matches = []
  for m1,m2 in matches:
    if m1.distance < 0.8 * m2.distance:
      good_matches.append(m1)

  return good_matches

matches = keypoint_matchings(img1, img2)
#verify by printing 
print(matches[1])